import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#fedeb2',
        'primary': '#000000',
        'inverse-surface': '#2f3130',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8e8e6',
        'on-primary-container': '#76849f',
        'primary-fixed': '#d6e3ff',
        'surface-container-low': '#f4f4f2',
        'on-surface-variant': '#44474d',
        'primary-container': '#0d1c32',
        'secondary': '#725b38',
        'surface': '#f9f9f7',
        'surface-container-highest': '#e2e3e1',
        'tertiary-container': '#111c2d',
        'on-primary-fixed-variant': '#39475f',
        'on-error': '#ffffff',
        'on-surface': '#1a1c1b',
        'surface-dim': '#dadad8',
        'on-background': '#1a1c1b',
        'secondary-fixed': '#fedeb2',
        'outline-variant': '#c5c6cd',
        'secondary-fixed-dim': '#e0c298',
        'on-secondary-container': '#78603e',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#111c2d',
        'inverse-primary': '#b9c7e4',
        'on-secondary-fixed-variant': '#584323',
        'surface-bright': '#f9f9f7',
        'outline': '#75777e',
        'surface-variant': '#e2e3e1',
        'tertiary-fixed': '#d8e3fb',
        'on-secondary-fixed': '#281800',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f1f1ef',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#bcc7de',
        'surface-tint': '#515f78',
        'background': '#f9f9f7',
        'on-tertiary': '#ffffff',
        'tertiary': '#000000',
        'surface-container': '#eeeeec',
        'on-tertiary-fixed-variant': '#3c475a',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#b9c7e4',
        'on-primary-fixed': '#0d1c32',
        'on-tertiary-container': '#79849a',
        'on-secondary': '#ffffff',

        // Legacy / Cyber accents
        surfaceLight: '#111827',
        borderGlow: 'rgba(34, 211, 238, 0.25)',
        cyanGlow: '#22d3ee',
        blueGlow: '#3b82f6',
        fqoreGold: '#F59E0B',
        fqoreAmber: '#D97706',
        fqoreYellow: '#EAB308',
        fqoreEmerald: '#10B981',
        fqoreDark: '#07090E',
        fqoreCard: '#0D111A',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
        'space-md': '1rem',
        'margin': '1rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'gutter-desktop': '2rem',
        'gutter-tablet': '1.5rem',
        'gutter': '1rem',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'display-lg': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'glow-gold': '0 0 25px rgba(245, 158, 11, 0.35)',
        'glow-emerald': '0 0 25px rgba(16, 185, 129, 0.35)',
        'glow-cyan': '0 0 25px rgba(34, 211, 238, 0.3)',
        'glow-cyan-lg': '0 0 50px rgba(34, 211, 238, 0.45)',
        'glow-blue': '0 0 35px rgba(59, 130, 246, 0.35)',
        'chrome-btn': '0 4px 20px rgba(255, 255, 255, 0.15), 0 0 15px rgba(34, 211, 238, 0.25)',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 7s ease-in-out 2s infinite',
        'float-reverse': 'floatReverse 8s ease-in-out infinite',
        'marquee': 'marquee 25s linear infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        floatReverse: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(10px)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
