import { Plan } from './types';

export const DEFAULT_PLANS: Plan[] = [
  {
    _id: '6aa3c900e4017433da625f4e',
    name: 'Starter Plan',
    slug: 'starter',
    price: 59,
    currency: 'INR',
    description: 'Essential access to foundational business PDFs and stock market cheat sheets.',
    features: [
      'Access to Essential Business Model PDFs',
      'Stock Market Basics Cheat Sheets',
      'Full Web Reader Access',
      'Standard Resolution Charts & Figures',
      'Lifetime Revisions for Downloaded PDFs',
    ],
    badge: 'Basic Tier',
    popular: false,
    active: true,
    order: 1,
  },
  {
    _id: '6aa3c900e4017433da625f4f',
    name: 'Swing Trading Blueprint (Growth Plan)',
    slug: 'growth',
    price: 99,
    currency: 'INR',
    description: "The Beginner's Roadmap to Finding, Planning & Managing Swing Trades (15-Page Complete Guide by Samir Sarkar / FQore).",
    features: [
      'Complete 15-Page High-Conviction Blueprint PDF (Protected)',
      'Swing Trading Setup Framework & Entry Timing Models',
      'Risk-to-Reward Calculator & Position Sizing Formulas',
      'Core 4 Video Masterclasses (1080p Full HD)',
      'High-Resolution Download & Read Online Access',
      'Instant Email & Direct Device Delivery',
    ],
    badge: 'Most Popular / ₹99',
    popular: true,
    active: true,
    order: 2,
  },
  {
    _id: '6aa3c900e4017433da625f50',
    name: 'Trading Masterclass (Premium All-Access)',
    slug: 'premium',
    price: 149,
    currency: 'INR',
    description: 'Complete 20-Page Institutional E-Book All-Access: From Beginner to Systematic Trading Blueprint.',
    features: [
      'Complete 20-Page Institutional E-Book Dossier PDF (Protected)',
      'Order Flow, Gamma Exposures & Liquidity Heatmap Systems',
      'DCF Valuation & M&A Due Diligence Models (Excel)',
      'Full Video Masterclass Cohort Sessions & Direct Mentorship',
      'Lifetime Updates & Free Access to Future Playbooks',
      'Direct Author / Institutional Desk Access Pass',
    ],
    badge: 'Institutional All-Access / ₹149',
    popular: false,
    active: true,
    order: 3,
  },
];
